language: generic

sudo: required

services:
  - docker

before_script:
- docker build -t stm32f7-discovery .

script:
- docker run stm32f7-discovery sh -c "
    set -e;
    pwd; ls;
    echo `pwd`;
    cargo build;
    cd blinking_led;
    cargo update;
    cargo build;
    cd ../blinking_led_with_interrupts;
    cargo update;
    cargo build;
  "
